rvm: 1.9.2
before_script: sudo apt-get install xvfb iceweasel; Xvfb :99 -ac -screen 0 1024x768x16
script: DISPLAY=:99.0 RAILS_ENV=test bundle exec rake db:create db:migrate spec cucumber --trace 2>&1
